### PR TITLE
Stop overriding Sentry default options

### LINKED ISSUE #22: Enable uncaught exception default integration
We should change the default setting of Sentry integration to include the `uncaughtException` handler.

### LINKED ISSUE #32: Fix documentation of onErrorFactory
The documentation cites `fastify` as a parameter but it has been removed.

### PR DESCRIPTION
**Pull request by dnlup**
In this PR I am removing the plugin  behaviour  of overriding Sentry default options, which was causing more harm than good in a lot of use cases. There is also a minor fix on the documentation about the `onErrorFactory`.

It is a breaking change.

Closes #22 ,closes #32

### CODE REVIEW

**Comment by dnlup** [comment]
I think most of the chains are from unmerged commits.

**Comment by dnlup** [comment]
I should have fixed the errors that we had only in the CI. It wasn't the DSN though.

**Review by antoniomuso — APPROVED** [review]
LGTM! Good Job :rocket:

File: index.js [hunk 1]
```diff
@@ -55,29 +55,17 @@ module.exports = fp(
...
-            release,
-            autoSessionTracking,
-            defaultIntegrations,
-            integrations,
-            ...sentryOptions,
-        });
-
-        if (!dsn) {
+        sentryOptions = sentryOptions || {};
+        Sentry.init(sentryOptions);
```
Comment (antoniomuso) [inline index.js:67]: Why now don't you pass as input the environment variables to the sentry Client?

**Review by simonecorsi — CHANGES_REQUESTED** [review]
Can we add a migration guide for our projects that uses the pre-breaking?

File: index.js (hunk 1 above)
Comment (dnlup) [reply index.js:67]: I am not sure if I understand what you mean, but the environment variables are parsed by the Sentry SDK

Comment (antoniomuso) [reply index.js:67]: What I mean is that now you have unpacked the environment, and inside `sentryOptions` is no more present.

**Comment by dnlup** [comment]
> Can we add a migration guide for our projects that uses the pre-breaking?

Sure thing

File: index.js (hunk 1 above)
Comment (dnlup) [reply index.js:67]: Ok, the `environment` is still setup to a default value by the sdk and I think it might be the same value we used. The other variables are either the ones we should not override anymore, or didn't have default value.

Comment (antoniomuso) [reply index.js:67]: Ok, thanks for the clarification.
